### PR TITLE
Better handle errors in promise chains

### PR DESCRIPTION
**Pull request by joakin**
Mostly surfacing them so that the API consumer gets them instead of leaving the request without response waiting to time out.

### CODE REVIEW

**Comment by phuedx** [comment]
Mind if I squash the commits when you've fixed up 2965854?

**Comment by joakin** [comment]
Sure! I'll do it when adding the status code.

**Comment by joakin** [comment]
👍❓

**Comment by phuedx** [comment]
I reformatted your commit message as there was a line over 72 characters long. Your patch has been merged but it has a different SHA, b18d30c, which this means that GitHub won't automatically close this PR.

**Comment by joakin** [comment]
\o/

**Pull request closed without merging**
